name: example
description: An example project for flutter_widget.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.5 <4.0.0'
  flutter: '>=3.13.0'

dependencies:
  flutter:
    sdk: flutter

  icheer_widget:
    path: ../
  cupertino_icons: ^1.0.8
  get: ^4.6.6
  fl_chart: ^0.69.0
  excel: ^4.0.6
  open_file: ^3.5.8
  path_provider: ^2.1.4
  path: ^1.9.0
  share_plus: ^10.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:

  uses-material-design: true

  assets:
    - assets/
    - assets/animations/
    - assets/images/
